#=========================================================
# Copyright (c) 2021 baiyunxue
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/baiyunxue/Compile-LEDE
# Description: Build OpenWrt using GitHub Actions
#=========================================================

name: by-immortalwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查。。。。。。初始环境
        uses: actions/checkout@main

      - name: 正在载入Ubuntu。。。。。
        run: |
          sudo apt-get update -y
          sudo apt-get full-upgrade -y
          sudo apt-get install -y build-essential cmake asciidoc binutils bzip2 gawk gettext git \
            libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex \
            uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo \
            libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool \
            autopoint ccache curl wget vim nano python2.7 python3 python3-pip python3-ply haveged lrzsz \
            device-tree-compiler scons antlr3 gperf intltool mkisofs rsync

      - name: 克隆源代码
        run: |
          git clone -b openwrt-18.06 --single-branch https://github.com/immortalwrt/immortalwrt openwrt
          cd openwrt
          sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
          sed -i 's/disabled=1/disabled=0/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: SSH连接至Actions云服务器
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   
      - name: 下载编译所需要的dl包
        run: |
          cd openwrt
          make -j8 download V=s 
      
      - name: 开始编译固件：请稍等..........(大概2小时左右)
        run: |
          cd openwrt
          make -j1 V=s
     
      - name : 上传固件
        uses: actions/upload-artifact@main
        with:
          name: by-immortalwrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin
