#=========================================================
# Copyright (c) 2021 baiyunxue
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/baiyunxue/Compile-Lede-Openwrt
# Description: Build OpenWrt using GitHub Actions
#=========================================================

name: by-Openwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查。。。。。。初始环境
        uses: actions/checkout@main

      - name: 正在载入Ubuntu。。。。。
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
            python3-distutils python3-setuptools python3-dev rsync subversion swig time \
            xsltproc zlib1g-dev 

      - name: 克隆源代码
        run: |
          git clone -b openwrt-19.07 https://github.com/openwrt/openwrt
          cd openwrt
          sed -i '$a src-git ZDY https://github.com/baiyunxue/ZDY.git' feeds.conf.default
      #   sed -i '$a src-git kenzok8 https://github.com/kenzok8/small-package.git;19.07' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: SSH连接至Actions云服务器
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
          
      - name: 开始编译固件：请稍等..........(大概2小时左右)
        run: |
          cd openwrt
          make -j1 V=s
          
      - name : 上传固件
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin
