#=========================================================
# Copyright (c) 2021 baiyunxue
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/baiyunxue/Compile-Lede-Openwrt
# Description: Build OpenWrt using GitHub Actions
#=========================================================

name: by-Openwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 正在载入Ubuntu。。。。。
        run: |
          sudo apt-get update
          sudo apt-get -y install binutils bzip2 diff find flex gawk gcc-6+ getopt grep install libc-dev libz-dev make4.1+ perl python3.6+ rsync subversion unzip which

      - name: 克隆源代码
        run: |
          git clone -b openwrt-19.07 https://github.com/openwrt/openwrt by-openwrt
          cd by-openwrt
          sed -i '$a src-git kiddin9 https://github.com/kiddin9/openwrt-packages.git
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: SSH连接至Actions云服务器
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   
      - name: 下载编译所需要的dl包
        run: |
          cd by-openwrt
          make -j8 download V=s   
          
      - name: 开始编译固件：请稍等..........(大概2小时左右)
        run: |
          cd by-openwrt
          make -j1 V=s
          
      - name : 上传固件
        uses: actions/upload-artifact@main
        with:
          name: by-OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin
